### ISSUE TITLE
License

### ISSUE THREAD

**Issue by whoenig** [peteflorence/crazyflie-CAD#1]
What is the license for the CAD files? I would like to use a modified version for the Crazyflie ROS package (http://wiki.ros.org/crazyflie).

**Comment by peteflorence** [comment]
We'd be glad for you to use it for ROS!

I'm traveling now but will put a license on it soon. (Hopefully later
today). Does that sound okay?

**Comment by peteflorence** [comment]
@whoenig I've added a BSD-3 license.  Please let me know if you need any help editing a version for the CrazyFlie ROS package?
